build:
	docker compose build authenticate-service-api;
app:
	docker-compose -f docker-compose.yml down; docker-compose -f docker-compose.yml up;
bash:
	docker compose run authenticate-service-api bash;