
### api register a account
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "username": "vuluu2kkkkkkkk",
  "password": "vuluu2k",
  "email": "vuluu2kkkkk@gmail.com",
  "last_name": "luu",
  "first_name": "vu",
  "phone_number": "0123456789"
}
### api logim a account
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "long2003",
  "password": "long2003"
}

### check verifly 
GET http://localhost:3000/api/v1/auth/info
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ3MjkxN2IyYzUxOWM4ZmIxNDgxMzYiLCJmdWxsbmFtZSI6InN5IGxvbmciLCJpYXQiOjE2OTkzNTEwMTYsImV4cCI6MTcwMjk1MTAxNn0.ep4WHZ2QV4aw8JMpK52lLjSEcZEdOnYf4XRkhZmW6cE
### logout
POST http://localhost:3000/api/v1/auth/logout
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ3MjkxN2IyYzUxOWM4ZmIxNDgxMzYiLCJmdWxsbmFtZSI6InN5IGxvbmciLCJpYXQiOjE2OTkzNTA5MjQsImV4cCI6MTY5OTM1MDk1NH0.YSYlSD_RE32rATwr6T9JdE2B9SyB9gZ4ema5pLWQGMU"
}
###4
POST http://localhost:3000/api/v1/auth/refresh
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ3MjkxN2IyYzUxOWM4ZmIxNDgxMzYiLCJmdWxsbmFtZSI6InN5IGxvbmciLCJpYXQiOjE2OTkzNDg3NzAsImV4cCI6NDI5MTM0ODc3MH0.3RE2WVJeAf2pQcrmAGMiedEj0XkISNLPiz2s37a02-g"
}